# Generated by Django 6.0.2 on 2026-03-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='genres_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='main_genre',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='seasons',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
